version: "3"
services:
  accural:
    container_name: accural
    build: 
      dockerfile: build/docker/accural/Dockerfile
      context: .
    ports:
      - "8001:8080"
    expose:
      - "8080"

  gophermart:
    container_name: gophermart
    build: 
      dockerfile: build/docker/gophermart/Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
       postgres-db:
         condition: service_healthy
    environment:
      - RUN_ADDRESS=0.0.0.0:8080
      - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db/${POSTGRES_DB}?sslmode=disable
      - ACCRUAL_SYSTEM_ADDRESS=http://accural:8080
    
  postgres-db:
    container_name: loyalty-postgres-db
    image: postgres:15.4-alpine3.18
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=${POSTGRES_USER:?Please configure POSTGRES_USER in the .env file}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Please configure POSTGRES_PASSWORD in the .env file}
      - POSTGRES_DB=${POSTGRES_DB:?Please configure POSTGRES_DB in the .env file}