name: Test and coverage

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
            go-version: '1.22'
      - name: Run coverage
        run: |
            cd ./src
            go test -race -coverprofile=coverage.out -covermode=atomic ./...
            go tool cover -html=coverage.out -o coverage.html
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: ScreamSoul/go-musthave-diploma
      - name: Add coverage.html to artifacts
        uses: actions/upload-artifact@v1
        with:
            name: coverage-html
            path: ./src/coverage.html
        
